services:

  database:
    build:
      context: ./database
    image: database_image
    environment:
      POSTGRES_DB: docker_app_db
      POSTGRES_USER: docker_app
      POSTGRES_PASSWORD: docker_app
    volumes:
      - todo_db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", -"U","docker_app"]
      interval: 5s
      timeout: 5s
    # deploy:
    #   replicas: 3

  backend:
    build:
      context: ./backend
    image: backend_image
    environment:
      HOST: database
      PORT: 5432
      DB: docker_app_db
      DB_USERNAME: docker_app
      DB_PASSWORD: docker_app
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8000/test"]
      interval: 5s
      timeout: 5s
    depends_on:
      database:
        condition: service_healthy


  nginx:
    build:
      context: ./frontend
    image: frontend_image
    ports:  
      - 80:80
    volumes:
      - ${PWD}/frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy


volumes:
  todo_db:
    name: todo_db
